#!/usr/bin/env bash

APP="desqer"

BUILD_HOST="api.desqer.com"
BUILD_USER="desqer"
BUILD_AT="/home/desqer/api/source/"

PRODUCTION_HOSTS="api.desqer.com"
PRODUCTION_USER="desqer"
DELIVER_TO="/home/desqer/api/"

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/desqer/api/shared/prod.secret.exs"

  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}
